version: "3.6"

services:
  so1:
    networks:
      splunknet:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: so1
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_APPS_URL
      - SPLUNKBASE_USERNAME
      - SPLUNKBASE_PASSWORD
      - SPLUNK_PASSWORD
      - JAVA_VERSION=openjdk:11
      - TZ=${TZ}
    ports:
      - 8000:8000
      - 8089:8089
      - 9998:9998
      - 9999:9999
    volumes:
      - so1-var:/opt/splunk/var
      - so1-etc:/opt/splunk/etc
    restart: always

  db:
    networks:
      splunknet:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: ${TZ}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - .${INIT_DIR}:/docker-entrypoint-initdb.d

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  so1-var:
  so1-etc:
  db-data:
