#!/bin/bash
source .env
#
# Create MySQL initilization files from generated data
#

SQL="${INIT_DIR}/create-db.sql"

cat <<EOF > $SQL
# Generated by `basename "$0"`
# Create MySQL schema from generated data
# And load tables from generated csv data
USE $MYSQL_DATABASE;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';
EOF

# Create Schema
for f in `ls $DATA_DIR/*.csv`;
do
    csvsql -i mysql -d ',' $f >> $SQL
    table=${f##*/}
    table=${table%.csv}
    echo "LOAD DATA INFILE '${f:1}' INTO TABLE \`$table\`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'
    IGNORE 1 ROWS;" >> $SQL
done
