#!/bin/bash
source .env
SQL=".${INIT_DIR}/create-db.sql"

cat <<EOF > $SQL
#
# Generated by `basename "$0"` on `date`
#
USE $DB_NAME;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';
#
# Create MySQL schema from generated data
# And load tables from generated csv data
#
EOF

for f in `ls .$CSV_DIR/*.csv`;
do
    csvsql -i mysql -d ','  --snifflimit 0 $f >> $SQL
    table=${f##*/}
    table=${table%.csv}
    echo "LOAD DATA LOCAL INFILE '${f:1}' INTO TABLE \`$table\`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'
    IGNORE 1 ROWS;" >> $SQL
done
