[install]
is_configured = 0
install_source_checksum = 3294f0e61a503519b60107bee6ef402687253bed

[launcher]
author = D. Dessy
description = Dashboards from DB queries
version = 0.0.0

[package]
check_for_updates = 0

[ui]
is_visible = 1
label = Splunk DB
