USE splunkdb;
GRANT ALL PRIVILEGES ON splunkdb.* TO 'splunk'@'%';
CREATE TABLE `dc-svc` (
	host VARCHAR(12) NOT NULL,
	app VARCHAR(17) NOT NULL,
	status VARCHAR(2) NOT NULL
);
LOAD DATA INFILE '/data/dc-svc.csv' INTO TABLE `dc-svc`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
CREATE TABLE dc (
	dc_name VARCHAR(12) NOT NULL
);
LOAD DATA INFILE '/data/dc.csv' INTO TABLE `dc`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
CREATE TABLE `send-receive` (
	sender VARCHAR(17) NOT NULL,
	receiver VARCHAR(17) NOT NULL,
	bytes DECIMAL(38, 0) NOT NULL
);
LOAD DATA INFILE '/data/send-receive.csv' INTO TABLE `send-receive`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
CREATE TABLE services (
	service_name VARCHAR(17) NOT NULL
);
LOAD DATA INFILE '/data/services.csv' INTO TABLE `services`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
CREATE TABLE users (
	username VARCHAR(17) NOT NULL
);
LOAD DATA INFILE '/data/users.csv' INTO TABLE `users`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
CREATE TABLE webmail (
	host VARCHAR(37) NOT NULL,
	status VARCHAR(2) NOT NULL
);
LOAD DATA INFILE '/data/webmail.csv' INTO TABLE `webmail`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
